In [1]:
## Imports. This contains some imports not required for this notebook. 

import sys
import os
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import pylab                   # Needed to plot histograms.
from astropy.io import fits                    # Need this if you want to use astropy.io io objects.
from astropy.stats import mad_std              # The median absolute deviation, a more robust estimator than std.
from PIL import Image
from scipy.ndimage import gaussian_filter
from scipy import signal

'''Filter out warnings. May or may not need this. But shouldn't hurt to put it in.
This is the "new" code for avoiding warnings-- seems to work better. Copied from an SDSS notebook.'''
import warnings
warnings.filterwarnings('ignore')

sys.path.append(r'C:\Users\owenm\Documents\ASTR 21200 2019\Software\a212pylibs\datapype')

from datafits import DataFits

In [3]:
# Specify the path to the data directory.
# datapath = '/Users/alex/_observing/24-inch/2018/manual_dark/darks_180420'
datapath = r'C:\Users\owenm\Documents\ASTR 21200 2019\Data\Project\dark'
savepath = r'C:\Users\owenm\Documents\ASTR 21200 2019\Data\BadPixelsFitss'

In [4]:
## List files in the the data directory.

whichpath = datapath

## For ALL the files in the directory.
# allfiles = [f for f in os.listdir(datapath)]

## Various list comprehensions can pick out files with particular characteristics.
allfiles = [f for f in os.listdir(whichpath) if '.fit' in f and ('bias.' in f) and 'mdark' not in f]

allfiles = sorted(allfiles)       ## This is necessary on my Mac, may not be for others?
for i in range(len(allfiles)):
    print( i, allfiles[i])
    

0 dark_190421_AA-001_bias.fit
1 dark_190421_AA-002_bias.fit
2 dark_190421_AA-003_bias.fit
3 dark_190421_AA-004_bias.fit
4 dark_190421_AA-005_bias.fit
5 dark_190421_AA-006_bias.fit
6 dark_190421_AA-007_bias.fit
7 dark_190421_AA-008_bias.fit
8 dark_190421_AA-009_bias.fit
9 dark_190421_AA-010_bias.fit
10 dark_190421_AA-011_bias.fit
11 dark_190421_AA-012_bias.fit
12 dark_190421_AA-013_bias.fit
13 dark_190421_AA-014_bias.fit
14 dark_190421_AA-015_bias.fit
15 dark_190421_AA-016_bias.fit
16 dark_190421_AA-017_bias.fit
17 dark_190421_AA-018_bias.fit
18 dark_190421_AA-019_bias.fit
19 dark_190421_AA-020_bias.fit
20 dark_190421_AA-021_bias.fit
21 dark_190421_AA-022_bias.fit
22 dark_190421_AA-023_bias.fit
23 dark_190421_AA-024_bias.fit
24 dark_190421_AA-025_bias.fit
25 dark_190421_AA-026_bias.fit
26 dark_190421_AA-027_bias.fit
27 dark_190421_AA-028_bias.fit
28 dark_190421_AA-029_bias.fit
29 dark_190421_AA-030_bias.fit
30 dark_190504_AB-001_bias.fit
31 dark_190504_AB-002_bias.fit
32 dark_190504_AB-

In [5]:
## Construct a list of files you wish to view and/or process.

acceptlist = True             # True if you want to accept all the files in allfiles.
contiguous = True             # True if you want to accept a contiguous subset of allfiles.
startfile, endfile = 0,9      # The first and last files in a contiquous subset.
flist = [0,3,4,5,6,7,8]        # An explicit list of the files you want to accept.

if acceptlist == True:
    files = allfiles
    for i in range(len(files)):
        print(i, files[i])
else:
    if contiguous == True:
        files = allfiles[startfile:endfile+1]
        for i in range(len(files)):
            print( i, files[i])
    else:
        files = []
        for i in range(len(flist)):
            files.append(allfiles[flist[i]])
        for i in range(len(files)):
            print( i, flist[i], files[i])

0 dark_190421_AA-001_bias.fit
1 dark_190421_AA-002_bias.fit
2 dark_190421_AA-003_bias.fit
3 dark_190421_AA-004_bias.fit
4 dark_190421_AA-005_bias.fit
5 dark_190421_AA-006_bias.fit
6 dark_190421_AA-007_bias.fit
7 dark_190421_AA-008_bias.fit
8 dark_190421_AA-009_bias.fit
9 dark_190421_AA-010_bias.fit
10 dark_190421_AA-011_bias.fit
11 dark_190421_AA-012_bias.fit
12 dark_190421_AA-013_bias.fit
13 dark_190421_AA-014_bias.fit
14 dark_190421_AA-015_bias.fit
15 dark_190421_AA-016_bias.fit
16 dark_190421_AA-017_bias.fit
17 dark_190421_AA-018_bias.fit
18 dark_190421_AA-019_bias.fit
19 dark_190421_AA-020_bias.fit
20 dark_190421_AA-021_bias.fit
21 dark_190421_AA-022_bias.fit
22 dark_190421_AA-023_bias.fit
23 dark_190421_AA-024_bias.fit
24 dark_190421_AA-025_bias.fit
25 dark_190421_AA-026_bias.fit
26 dark_190421_AA-027_bias.fit
27 dark_190421_AA-028_bias.fit
28 dark_190421_AA-029_bias.fit
29 dark_190421_AA-030_bias.fit
30 dark_190504_AB-001_bias.fit
31 dark_190504_AB-002_bias.fit
32 dark_190504_AB-

# Task 1. Creating Faulty Non-Noisy Pixels Fits

In [6]:
'''Make a stack of images, a list of headers from those images, and calculate some medians and stds
that will help set autoscaling parameters.'''


image = np.zeros((len(files), 1024,1024))
imedian = np.zeros((len(files)))          
istd = np.zeros((len(files)))              
madstd = np.zeros((len(files))) 
headlist = []  
print('image.shape =', image.shape)
for i in range(len(files)):


#############################################################################
    # Use this code block if you want to use the standard astropy.io package.
    fitsfilename = os.path.join(datapath, files[i])    # Full path to a fitsfile.
    hdulist = fits.open(fitsfilename)                  # Open a fits file as an hdulist object.
    hdu0 = hdulist[0]                                  # Define a fits object as the 0th hdu in the fitsfile.
    image[i] = hdu0.data * 1.0                         # Define image in stack as float of data in the 0th hdu.
    headlist.append(hdu0.header)                       # Append the header of the fits object to the header list.
    print('')
    print(i,files[i])
###############################################################################    
    
    ## Calculate some medians and stds to use in autoscaling that aren't unduly biased by extreme values.
    ## Optionally, print out masked and unmasked values to explore the effects of extreme values on the statistics.
    
    madstd[i] = mad_std(image[i],ignore_nan=True)
    imedian[i] = np.nanmedian(image[i])
    istd[i] = np.nanstd(image[i])

image.shape = (301, 1024, 1024)

0 dark_190421_AA-001_bias.fit

1 dark_190421_AA-002_bias.fit

2 dark_190421_AA-003_bias.fit

3 dark_190421_AA-004_bias.fit

4 dark_190421_AA-005_bias.fit

5 dark_190421_AA-006_bias.fit

6 dark_190421_AA-007_bias.fit

7 dark_190421_AA-008_bias.fit

8 dark_190421_AA-009_bias.fit

9 dark_190421_AA-010_bias.fit

10 dark_190421_AA-011_bias.fit

11 dark_190421_AA-012_bias.fit

12 dark_190421_AA-013_bias.fit

13 dark_190421_AA-014_bias.fit

14 dark_190421_AA-015_bias.fit

15 dark_190421_AA-016_bias.fit

16 dark_190421_AA-017_bias.fit

17 dark_190421_AA-018_bias.fit

18 dark_190421_AA-019_bias.fit

19 dark_190421_AA-020_bias.fit

20 dark_190421_AA-021_bias.fit

21 dark_190421_AA-022_bias.fit

22 dark_190421_AA-023_bias.fit

23 dark_190421_AA-024_bias.fit

24 dark_190421_AA-025_bias.fit

25 dark_190421_AA-026_bias.fit

26 dark_190421_AA-027_bias.fit

27 dark_190421_AA-028_bias.fit

28 dark_190421_AA-029_bias.fit

29 dark_190421_AA-030_bias.fit

30 dark_190504_AB


252 dark_190504_AD-149_bias.fit

253 dark_190504_AD-150_bias.fit

254 dark_190504_AD-151_bias.fit

255 dark_190504_AD-152_bias.fit

256 dark_190504_AD-153_bias.fit

257 dark_190504_AD-157_bias.fit

258 dark_190504_AD-158_bias.fit

259 dark_190504_AD-159_bias.fit

260 dark_190504_AD-160_bias.fit

261 dark_190504_AD-161_bias.fit

262 dark_190504_AD-162_bias.fit

263 dark_190504_AD-163_bias.fit

264 dark_190504_AD-164_bias.fit

265 dark_190504_AD-165_bias.fit

266 dark_190504_AD-166_bias.fit

267 dark_190504_AD-167_bias.fit

268 dark_190504_AD-168_bias.fit

269 dark_190504_AD-169_bias.fit

270 dark_190504_AD-170_bias.fit

271 dark_190504_AD-171_bias.fit

272 dark_190504_AD-172_bias.fit

273 dark_190504_AD-173_bias.fit

274 dark_190504_AD-174_bias.fit

275 dark_190504_AD-175_bias.fit

276 dark_190504_AD-176_bias.fit

277 dark_190504_AD-177_bias.fit

278 dark_190504_AD-178_bias.fit

279 dark_190504_AD-179_bias.fit

280 dark_190504_AD-180_bias.fit

281 dark_190504_AD-181_bias.fit

282 dark_

In [7]:
bad = 0
for i in range(len(image)):
    istand = image[i] - imedian[i]
    bad += (istand > istd[i])
    bad += (istand < -istd[i])
for j in range(len(sum(bad))):
    print(str(j) + ':' + str(sum(bad)[j]))

0:92637
1:98701
2:84049
3:77441
4:72619
5:72022
6:67821
7:66289
8:78392
9:59800
10:57317
11:92115
12:57178
13:63431
14:51272
15:52987
16:47598
17:50281
18:59729
19:32926
20:50914
21:43172
22:49499
23:41945
24:45537
25:37168
26:40795
27:44781
28:36905
29:38441
30:37169
31:36411
32:34183
33:33898
34:32511
35:34997
36:31733
37:29822
38:28798
39:29412
40:27145
41:27243
42:26498
43:27789
44:27045
45:23702
46:23912
47:24394
48:23359
49:22577
50:22231
51:21528
52:21363
53:20112
54:23045
55:18415
56:21022
57:18596
58:20379
59:22573
60:17895
61:19564
62:18576
63:19573
64:17689
65:18811
66:20910
67:17474
68:18133
69:15359
70:17004
71:17106
72:17098
73:19701
74:15673
75:14952
76:15160
77:14472
78:13737
79:13940
80:19590
81:13194
82:12778
83:12793
84:12551
85:12391
86:12687
87:39141
88:11798
89:12335
90:11156
91:11457
92:10995
93:11409
94:10819
95:13318
96:10706
97:10257
98:10598
99:9571
100:10538
101:9742
102:9402
103:10809
104:9409
105:9795
106:9362
107:9456
108:9407
109:8853
110:8601
111:8719
1

931:5174
932:4980
933:4990
934:4920
935:5098
936:5173
937:5066
938:5995
939:4978
940:4923
941:4913
942:4897
943:4912
944:4981
945:4969
946:4781
947:5757
948:5053
949:5032
950:4843
951:4869
952:4734
953:4744
954:4877
955:5179
956:5101
957:4969
958:5043
959:4847
960:4896
961:4930
962:4828
963:5024
964:4886
965:5046
966:4828
967:4912
968:5056
969:4896
970:5281
971:4723
972:5089
973:4828
974:4934
975:4803
976:4753
977:4790
978:4864
979:4766
980:4811
981:4805
982:4815
983:4951
984:4867
985:4821
986:5052
987:4911
988:4935
989:5156
990:4874
991:4870
992:5207
993:5421
994:4978
995:4876
996:4858
997:5101
998:5055
999:5107
1000:4816
1001:5006
1002:4916
1003:4992
1004:5009
1005:224364
1006:4478
1007:4940
1008:4770
1009:5095
1010:4732
1011:4784
1012:4730
1013:4817
1014:4649
1015:5147
1016:4807
1017:4938
1018:4845
1019:9133
1020:4591
1021:4827
1022:4636
1023:4586


In [8]:
#Creating a map of how often the pixels have been bad

bads = np.zeros((1024,1024))

imedian2 = np.zeros((len(files)))           # 1D numpy array to hold array medians.
istd2 = np.zeros((len(files)))              # 1D numpy array to hold array stds.

for i in range(len(files)):
    imedian2[i] = np.nanmedian(image[i,200:,:])
    istd2[i] = np.nanstd(image[i,200:,:])
    #sets the median and std arrays to hold the median and std of each image

for i in range(len(image)):
    istand = image[i] - imedian2[i]
    bad1 = (istand > istd2[i]) * 1
    #check if 1 standard deviation above the median
    bad2 = (istand < -istd2[i]) * 1
    #check if 1 standard deviation below the median
    bad = bad1 + bad2
    #will be 1 if one standard deviation off (above or below), 0 otherwise
    bads += bad
#counts the number

#print(bads)
#print(bads[:,1:])
b = bads[:, 200:]
print(b)
pix = np.zeros((1024,824))
ctr = 0
for i in range(1024):
    for j in range(824):
        if b[i,j] >= 20:
            ctr += 1
            pix[i,j] = 1
            #print(i,j)
#checks number of images for which a pixel is in "bads"
#if  >20 times bad, sets the pixel's corresponding point in "pix" to 1
            
print(str(ctr/(1024 * 824)))
#gives ratio of flaged pixels to all pixels

[[ 8.  6.  5. ...  6. 10.  8.]
 [10. 11.  5. ... 12. 11.  5.]
 [10. 12. 10. ...  9.  4. 13.]
 ...
 [15.  9.  3. ...  4. 16.  5.]
 [12.  7.  5. ... 10.  8. 13.]
 [ 9. 11. 14. ... 10. 11. 18.]]
0.00751976827973301


The above array gives the number of times, for each pixel, it has been deemed "bad" in the list of 300 darks.

If we check pixels that have been bad at least once: 49.2% of pixels meet this criteria If we check pixels that have been bad at least twice: 18.5% of pixels meet this criteria If we check pixels that have been bad at least 3 times: 8.28% of pixels meet this criteria If we check pixels that have been bad at least 4 times: 5.21% of pixels meet this criteria ...

Following code makes list

In [9]:
pix3 = np.zeros((1024,824))
#makes 2D a zero array that will become our final list of pixels to smooth over
mask3 = np.zeros((len(files),1024,824))
#zero array that will become a stack of masks
for i in range(1024):
    for j in range(824):
        if pix[i,j] == 1:
        #checks if pixel has been flagged by first algorithm, ignore if not
        #this next series of if statements considers several different possible pixel locations, with the goal of setting a "sur"
        #"sur" is a 2D array that is basically the pixel values of the surronding area
            if i >= 5 and i < 1019:
                #all of these use a row value between 5 and 1019
                if j >= 5 and j < 819:
                    sur = image[:,i-5:i+5,200+j-5:200+j+5]
                    #these pixels are in places where we can easily check the surronding area
                elif j < 5:
                    sur = np.append(image[:,i-5:i+5,200:200+j], image[:,i-5:i+5,-10+j:])
                    #if in a colum <5, wraps around the side to fill in the rest of the neighborhood
                else:
                    sur = np.append(image[:,i-5:i+5,j:], image[:,i-5:i+5,200:210-1024+j])
                    #column in last 5, wraps around to fill in rest of neighborhood
            elif i < 5:
                #all of these are for a row value less than 5
                if j >= 5 and j < 819:
                    sur = np.append(image[:,:i,200+j-5:200+j+5], image[:,-10+i:,200+j-5:200+j+5])
                    #accaptable column value, only need to wrap around top-bottom (rows)
                elif j < 5:
                    sur = np.append(image[:,:i,200:200+j], image[:,-10+i:,-10+j:])
                    #in a corner, wraps around to fill in both dimensions
                else:
                    sur = np.append(image[:,:i,j:], image[:,-10+i:,200:210-1024+j])
                    #second corner
            else:
                #row values in the last 5
                if j >= 5 and j < 819:
                    sur = np.append(image[:,i:,200+j-5:200+j+5], image[:, :10-1024+i,200+j-5:200+j+5])
                    #accaptable column value, only need to wrap around top-bottom (rows)
                elif j < 5:
                    sur = np.append(image[:,i:,200:200+j], image[:, :10-1024+i,-10+j:])
                    #third corner, wrap around in both dimensions
                else:
                    sur = np.append(image[:,i:,j:], image[:, :10-1024+i,200:210-1024+j])
                    #fourth corner
            surmed = np.nanmedian(sur)
            #sets surmed to median value of the surronding area
            surstd = np.nanstd(sur)
            #sets surstd to standard deviation of surronding area
            pmed = np.nanmedian(image[:,i,200+j])
            #finds the median value of the pixel accross all 32 images
            pix3[i,j] = abs(surmed - pmed) > surstd




## Making masks

In [11]:
# Make a median dark image from the image stack
dark = np.nanmedian(image, axis=0)
# make a bias file
bias = dark.copy()

# take a median row slice and smooth it
rowslice = np.median(bias, axis=0)
smooth_rowslice = signal.medfilt(rowslice, kernel_size=5)
smooth_rowslice = signal.savgol_filter(smooth_rowslice, window_length=101, polyorder=1)

In [12]:
#making initial mask
for i in range(1024):
    for j in range(824):          
            # sets to 1 if the median pixel value is more than one standard deviation away from the median of the surronding area
            if pix3[i,j] == 1:
                mask3[:,i,j] = image[:,i,200+j] - rowslice[200+j]
                #if pix3 is 1, sets the mask to be the value of the original image minus that value of the neighborhood median

In [13]:
#masking for pix3 

maskhelp2 = np.zeros((len(files),1024,200))
mask6 = np.append(maskhelp2,mask3, axis=2)

smoothed3 = image-mask6

DO NOT RUN


In [ ]:
# # Display all the images in the stack.
# figx, figy = 20,20   # Use these to reveal fine detail in images.
figx, figy = 8,8   # Use these to get a quick look and save space.

for i in range(len(files)):
    plt.figure(figsize = (figx,figy))
    vmx= imedian[i] + madstd[i] * 3.0
    vmn = imedian[i] - madstd[i] * 3.0
#     grid()
    plt.title(files[i] + '   Median =' + str(imedian[i]) + '    mad_std =' + str(madstd[i]))
    plt.imshow(smoothed[i],'gray',interpolation = 'nearest',vmax=vmx,vmin=vmn)

## creating and saving dead pixels fits

In [ ]:
#creating a workable data format for our boolean 2D Array
hdumy = fits.PrimaryHDU(pix3)

#Turning Workable Object into a fits
outd = fits.HDUList([hdumy])

## Construct a name and 'save directory' for the dark-subtracted, flatfielded image.
outname = 'bad_pixels' + '(INSERT NUMBER OR OTHER THING!!!!! OR ITLL BREAK SOME STUFF) 5' + '.fits'
outpath = savepath
print('outpath =',outpath)
outf = os.path.join(outpath,outname)
print('outname =',outname)

In [ ]:
## Now save the file (or not).
print(outf)
yes_or_no = input('Save file? Enter "y" or "n":')
if yes_or_no == 'y':
    outd.writeto(outf, overwrite = False)
    print( outname + ' has been saved.')
else:
    print( 'OK-- file was not saved.')

# outd.save(outf)

# Task 2 Creating Fits of Noisy Pixels




In [ ]:
#In dah_functions2 but my imports are being weird so i did it.
def stackfits(whichpath,files):
    '''
    Make a stack of images, a list of headers from those images, and 1D arrays for medians and mad_stds.
    whichpath:   The path to the fits files.
    files:  A list of files.
    '''

    ## Load the header of the first file in the list "files".
    df = DataFits()                                                   # Create a DataPype DataFits io object.
    df.loadhead(os.path.join(whichpath,files[0]))                # Loads just the header of the first file.
    ## Make variables for the numbers of rows and columns.
    rows, cols = df.header['naxis2'], df.header['naxis1']
    print('rows =',rows,'   cols =',cols)

    image = np.zeros((len(files), rows,cols))  # 3D numpy array to hold the stack of images.
    imedian = np.zeros((len(files)))           # 1D numpy array to hold array medians.
    imad = np.zeros((len(files)))            # 1D numpy array to hold Median absolute deviations.

    headlist = []                              # Empty list to hold the headers.
    print('image.shape =', image.shape)

    for i in range(len(files)):

    # ########################################################################   
        # Use this code block if you want to work with DataFits objects
        df = DataFits() 
        df.load(os.path.join(whichpath,files[i]))
        image[i] = df.imageget() * 1.0            # Load image data into numpy arrays and convert to float.
        headlist.append(df.header)
        imedian[i] = np.nanmedian(image[i])
        imad[i] = mad_std(image[i],ignore_nan=True)
        print('')
        print(i, files[i])
    # #########################################################################

    #############################################################################
    #     # Use this code block if you want to use the standard astropy.io package.
    #     fitsfilename = os.path.join(datapath, files[i])    # Full path to a fitsfile.
    #     hdulist = fits.open(fitsfilename)                  # Open a fits file as an hdulist object.
    #     hdu0 = hdulist[0]                                  # Define a fits object as the 0th hdu in the fitsfile.
    #     image[i] = hdu0.data * 1.0                         # Define image in stack as float of data in the 0th hdu.
    #     headlist.append(hdu0.header)                       # Append the header of the fits object to the header list.
    #     print('')
    #     print(i,files[i])
    ###############################################################################   
    return image, headlist, rows, cols, imedian, imad

In [ ]:
nbimage, nbheadlist, nbrows, nbcols, nbimedian, nbimad = stackfits(datapath,allfiles)

In [ ]:
#This is very important

bstackarray = nbimage

In [ ]:
#Analyze the variation of each pixel in the stack

bstackarray_std = np.std(bstackarray, axis=0)

bimg_global_std = np.median(bstackarray_std)

bnoisy_pixels = bstackarray_std > bimg_global_std*1.8

#we identified the pixels across the bias exposures whose values deviate from their respective means by 1.8 standard deviations
# this threshold was chosen based on visual comparisons with 1.7 standev and 1.9 standev

In [ ]:
#Identify and list the pixels that exceed the noise threshold

## plt.imshow(noisy_pixels)

blocs = np.array(np.where(bnoisy_pixels == True))
nbpix_bias = np.zeros((1019,1019)) 
for i in range(1019): #1024
    for j in range(1019): #1024
        if bnoisy_pixels[i,j] == True and j > 5:
            nbpix_bias[i,j] = 1
            

# for i in range(locs.shape[1]):
#     print(locs[0,i],locs[1,i])
    
#this prints a list of noisy pixels

In [ ]:
#Now we repeat the process for 020s
##This can be applied to any subset of raw fits images.
##In this example we used a single data set subdivided into exposure types

somefiles = [f for f in os.listdir(whichpath) if '.fit' in f and '_020s' in f and'stack' not in f]

somefiles = sorted(somefiles)       ## This is necessary on my Mac, may not be for others?


acceptlist = True             # True if you want to accept all the files in somefiles.
contiguous = True             # True if you want to accept a contiguous subset of somefiles.
startfile, endfile = 5,9      # The first and last files in a contiquous subset.
flist = [0,3,4,5,6,7,8]        # An explicit list of the files you want to accept.

n20image, n20headlist, n20rows, n20cols, n20imedian, n20imad = stackfits(datapath,somefiles)


n20stackarray = n20image

n20stackarray_std = np.std(n20stackarray, axis=0)

n20img_global_std = np.median(n20stackarray_std)

n20noisy_pixels = n20stackarray_std > n20img_global_std*1.8


n20locs = np.array(np.where(n20noisy_pixels == True))
npix_020s = np.zeros((1019,1019)) 
for i in range(1019): #1024
    for j in range(1019): #1024
        if n20noisy_pixels[i,j] == True and j > 5:
            npix_020s[i,j] = 1

In [ ]:
#Now we repeat the process for 040s
##This can be applied to any subset of raw fits images.
##In this example we used a single data set subdivided into exposure types

somefiles = [f for f in os.listdir(whichpath) if '.fit' in f and '_040s' in f and'stack' not in f]

somefiles = sorted(somefiles)       ## This is necessary on my Mac, may not be for others?


acceptlist = True             # True if you want to accept all the files in somefiles.
contiguous = True             # True if you want to accept a contiguous subset of somefiles.
startfile, endfile = 5,9      # The first and last files in a contiquous subset.
flist = [0,3,4,5,6,7,8]        # An explicit list of the files you want to accept.

n40image, n40headlist, n40rows, n40cols, n40imedian, n40imad = stackfits(datapath,somefiles)


n40stackarray = n40image

n40stackarray_std = np.std(n40stackarray, axis=0)

n40img_global_std = np.median(n40stackarray_std)

n40noisy_pixels = n40stackarray_std > n40img_global_std*1.8


n40locs = np.array(np.where(n40noisy_pixels == True))
npix_040s = np.zeros((1019,1019)) 
for i in range(1019): #1024
    for j in range(1019): #1024
        if n40noisy_pixels[i,j] == True and j > 5:
            npix_040s[i,j] = 1


In [ ]:
#Now we repeat the process for 100s
##This can be applied to any subset of raw fits images.
##In this example we used a single data set subdivided into exposure types

somefiles = [f for f in os.listdir(whichpath) if '.fit' in f and '_100s' in f and'stack' not in f]

somefiles = sorted(somefiles)       ## This is necessary on my Mac, may not be for others?


acceptlist = True             # True if you want to accept all the files in somefiles.
contiguous = True             # True if you want to accept a contiguous subset of somefiles.
startfile, endfile = 5,9      # The first and last files in a contiquous subset.
flist = [0,3,4,5,6,7,8]        # An explicit list of the files you want to accept.

n100image, n100headlist, n100rows, n100cols, n100imedian, n100imad = stackfits(datapath,somefiles)


n100stackarray = n100image

n100stackarray_std = np.std(n100stackarray, axis=0)

n100img_global_std = np.median(n100stackarray_std)

n100noisy_pixels = n100stackarray_std > n100img_global_std*1.8


n100locs = np.array(np.where(n100noisy_pixels == True))
npix_100s = np.zeros((1019,1019)) 
for i in range(1019): #1024
    for j in range(1019): #1024
        if n100noisy_pixels[i,j] == True and j > 5:
            npix_100s[i,j] = 1

In [ ]:
#Now we repeat the process for 0180s
##This can be applied to any subset of raw fits images.
##In this example we used a single data set subdivided into exposure types

somefiles = [f for f in os.listdir(whichpath) if '.fit' in f and '_180s' in f and'stack' not in f]

somefiles = sorted(somefiles)       ## This is necessary on my Mac, may not be for others?


acceptlist = True             # True if you want to accept all the files in somefiles.
contiguous = True             # True if you want to accept a contiguous subset of somefiles.
startfile, endfile = 5,9      # The first and last files in a contiquous subset.
flist = [0,3,4,5,6,7,8]        # An explicit list of the files you want to accept.

n180image, n180headlist, n180rows, n180cols, n180imedian, n180imad = stackfits(datapath,somefiles)


n180stackarray = n180image

n180stackarray_std = np.std(n180stackarray, axis=0)

n180img_global_std = np.median(n180stackarray_std)

n180noisy_pixels = n180stackarray_std > n180img_global_std*1.8


n180locs = np.array(np.where(n180noisy_pixels == True))
npix_180s = np.zeros((1019,1019)) 
for i in range(1019): #1024
    for j in range(1019): #1024
        if n180noisy_pixels[i,j] == True and j > 5:
            npix_180s[i,j] = 1

In [ ]:
#Stack the arrays of noisy pixels

dims = list(nbpix_bias.shape)
dims.append(5)
dims = [5,nbpix_bias.shape[0],nbpix_bias.shape[1]]
npixm = np.zeros(dims)
npixm[0,:,:]= nbpix_bias
npixm[1,:,:]= npix_020s
npixm[2,:,:]= npix_040s
npixm[3,:,:]= npix_100s
npixm[4,:,:]= npix_180s

In [ ]:
#creating a workable data format for our boolean 2D Array
hdumy = fits.PrimaryHDU(npixm)

#Turning Workable Object into a fits
outd = fits.HDUList([hdumy])

## Construct a name and 'save directory' for the dark-subtracted, flatfielded image.
outname = 'noisy_pixels' + '(INSERT NUMBER OR OTHER THING!!!!! OR ITLL BREAK SOME STUFF) 1' + '.fits'
outpath = savepath
print('outpath =',outpath)
outf = os.path.join(outpath,outname)
print('outname =',outname)

In [ ]:
## Now save the file (or not).
print(outf)
yes_or_no = input('Save file? Enter "y" or "n":')
if yes_or_no == 'y':
    outd.writeto(outf, overwrite = False)
    print( outname + ' has been saved.')
else:
    print( 'OK-- file was not saved.')

# outd.save(outf)